name: "Terraform pre-merge checks"
# Runs Terraform plan on pull requests
on:
  pull_request:
    types: ["opened", "reopened", "synchronize", "closed"]
    branches-ignore:
      - main

jobs:
  pre-checks:
    name: Code analysis and security checks
    runs-on: ubuntu-latest
    #checkov:skip=CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
    permissions:
      actions: write
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Generate GitHub token
        id: app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.SGC_GITHUB_APP_ID }}
          private_key: ${{ secrets.SGC_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Format Check
        run: terraform fmt -check
      
      - name: Terraform Init
        run: terraform init -backend=false
      
      - name: Terraform Validate
        run: terraform validate

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          skip_check: CKV_GIT_5,CKV_GIT_6,CKV2_GHA_1
          download_external_modules: true
          quiet: false
          framework: terraform
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
        
      - name: Terraform plan
        run: terraform plan
